# Generated by Django 4.1.4 on 2024-02-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='size',
            name='type_choice',
            field=models.CharField(choices=[('Vêtements-Femmes', 'Vêtements-Femmes'), ('Vêtements-Hommes', 'Vêtements-Hommes'), ('Vêtements-Enfants', 'Vêtements-Enfants'), ('Chaussures-Femmes', 'Chaussures-Femmes'), ('Chaussures-Hommes', 'Chaussures-Hommes'), ('Chaussures-Enfants', 'Chaussures-Enfants')], default='Vêtements-Femmes', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.size'),
        ),
    ]
