# Generated by Django 4.0 on 2022-01-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='a68d46c1-4f68-4646-ba66-0081204e17a0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.ForeignKey(blank=True, default='18fc9abc-2459-4551-b34a-0ae89181417b', on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.color'),
        ),
        migrations.AlterField(
            model_name='article',
            name='size',
            field=models.ForeignKey(blank=True, default='f816d8bb-3c3c-457f-b74c-ec4fa68aeb81', on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.size'),
        ),
    ]
