# Generated by Django 4.1.4 on 2024-02-23 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_condition_options_size_type_choice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={"ordering": ["type_choice"]},
        ),
    ]
