# Generated by Django 4.0 on 2022-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category_alter_article_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
