# Generated by Django 4.0 on 2022-01-07 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('user_choices', models.CharField(choices=[('PARTICULIER', 'PARTICULIER'), ('PROFESSIONNEL', 'PROFESSIONNEL')], default='PARTICULIER', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='user.png', null=True, upload_to='photos/%Y/%m')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('Dakar', 'Dakar'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaffrine', 'Kaffrine'), ('Kaolack', 'Kaolack'), ('Kedougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis'), ('Sedhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thies', 'Thiès'), ('Ziguinchor', 'Ziguinchor')], default='Dakar', max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('instagram', models.URLField(blank=True, max_length=400, null=True)),
                ('facebook', models.URLField(blank=True, max_length=400, null=True)),
                ('youtube', models.URLField(blank=True, max_length=400, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
