# Generated by Django 4.0 on 2022-01-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='article',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='firstname',
            new_name='username',
        ),
    ]
